services:
  app:
    container_name: volt-crypto-app
    build: .
    command: "npm run dev"
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
    networks:
      - volt-crypto-network
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env
    environment:
      - NODE_ENV=test
  db:
    container_name: volt-crypto-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vcrypto
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - volt-crypto-network
    restart: on-failure

networks:
  volt-crypto-network:

volumes:
  db-volume: